backend:
  name: git-gateway
  branch: main
media_folder: public/assets/images
public_folder: assets/images
collections:
  - name: "settings"
    label: "Settings"
    files:
      - label: "General"
        name: "general"
        file: "content/settings.md"
        fields:
          - label: "Social Media"
            name: "socialmedia"
            widget: "object" 
            fields:
              - {label: "Facebook", name: "facebook", widget: string, required: false}
              - {label: "Twitter", name: "twitter", widget: string, required: false}
              - {label: "Instagram", name: "instagram", widget: string, required: false}
          - label: "Booking"
            name: "booking"
            widget: object
            fields:
              - {label: "Button Text", name: "buttonText", widget: string}
              - {label: "Link", name: "link", widget: string}
              - {label: "Logo", name: "img", widget: string, required: false}
          - label: "Contact & Location"
            name: contact
            widget: object
            fields:
              - {label: "Phone", name: "phone", widget: string, required: false}
              - {label: "Email", name: "email", widget: string, required: false}
              - {label: "Address Line 1", name: "address1", widget: string, required: false}
              - {label: "Address Line 2", name: "address2", widget: string, required: false}
              - {label: "City", name: "city", widget: string, required: false}
              - {label: "State", name: "state", widget: string, required: false}
  - name: "pages"
    label: "Pages"
    files:
    - label: "Home"
      name: "home"
      file: "content/home.md"
      fields:
        - { label: "Title", name: "title", widget: "string"}
        - label: "Jumbotron" 
          name: "jumbotron"
          widget: "image"
          media_library:
            config:
              multiple: false
        - { label: "Jumtotron Text 1", name: "jumboText1", widget: "string", required: false }
        - label: "Testimonials"
          name: "testimonials"
          collapsed: false
          widget: "list"
          fields:
            - {label: Quote, name: quote, widget: text }
            - {label: Client, name: client, widget: string }
            - {label: Location, name: location, widget: string, required: false }
        - label: "Featured Images"
          name: featured
          widget: list
          min: 1
          max: 3
          fields:
            - label: Image
              name: image
              widget: image
              required: false
              media_library:
                config:
                  multiple: false  }
            - {label: Description, name: alt, widget: string, required: false  }

    - label: "About"
      name: "about"
      file: "content/about.md"
      fields:
        - { label: "Title", name: "title", required: false, widget: "string"}
        - { label: "Set up text", name: "apptText", required: false, default: "Set up an appointment with", widget: "string"}
        - label: Stylists
          name: stylists
          widget: list
          fields:
            - { label: First Name, name: nameFirst, widget: string }
            - { label: Last Name, name: nameLast, widget: string }
            - { label: Title, name: title, widget: string }
            - { label: About, name: about, widget: string }
            - label: "Image" 
              name: "image"
              widget: "image"
              default: ""
              media_library:
                config:
                  multiple: false
        
    - label: "Services"
      name: "services"
      file: "content/services.md"
      fields:
        - { label: "Title", name: "title", required: false, widget: "string"}
        - { label: "Body", name: "body", required: false, widget: "markdown"}
        - label: Services
          name: services
          widget: list
          fields:
            - { label: Service Name, name: service, widget: string }
            - { label: Service Price, name: price, widget: string }
            - { label: Description, name: description, widget: string }
    - label: "Gallery"
      name: "gallery"
      file: "content/gallery.md"
      fields:
        - { label: "Title", name: "title", required: false, widget: "string"}
        - { label: "Message", name: "message", widget: "string"}
        - label: "Images"
          name: "images"
          widget: "list"
          fields:
          - {label: Image, name: image, widget: image}
    - label: "Contact"
      name: "contact"
      file: "content/contact.md"
      fields:
        - { label: "Title", name: "title", required: false, widget: "string"}
        - { label: "Message", name: "message", widget: "string"}
        
    - label: "FAQ"
      name: "faq"
      file: "content/faq.md"
      fields:
        - { label: "Title", name: "title", required: false, widget: "string"}
        - { label: "Body", name: "body", required: false, widget: "markdown"}
        - label: "Questions and Answers"
          name: "faqs"
          widget: "list"
          fields:
            - {label: Question, name: question, widget: string }
            - {label: Answer, name: answer, widget: markdown }