backend:
  name: git-gateway
  branch: main
media_folder: public/img
public_folder: img
collections:
  - name: "settings"
    label: "Settings"
    files:
      - label: "Style Settings"
        name: "styleSettings"
        file: "content/settings.md"
        fields:
          - { label: "Title Font", name: "titleFont", widget: "string" }
  - name: "pages"
    label: "Pages"
    files:
    - label: "Home"
      name: "home"
      file: "content/home.md"
      fields:
        - { label: "Title", name: "title", widget: "string"}
        - { label: "Publish Date", name: "date", widget: "datetime" }
        - label: "Jumbotron" 
          name: "jumbotron"
          widget: "image"
          default: ""
          media_library:
            config:
              multiple: false
        - { label: "Jumtotron Text 1", name: "jumboText1", widget: "string", required: false }
        - { label: "Jumtotron Text 2", name: "jumboText2", widget: "string", required: false }
        
    - label: "About"
      name: "about"
      file: "content/about.md"
      fields:
        - { label: "Title", name: "title", required: false, widget: "string"}
        - { label: "Body", name: "body", required: false, widget: "markdown"}
        - { label: "Appt Text", name: "apptText", required: false, widget: "text"}
        - label: Stylists
          name: stylists
          widget: list
          fields:
            - { label: First Name, name: nameFirst, widget: text }
            - { label: Last Name, name: nameLast, widget: text }
            - { label: Title, name: title, widget: text }
            - { label: About, name: about, widget: string }
            - label: "Image" 
              name: "image"
              widget: "image"
              default: ""
              media_library:
                config:
                  multiple: false
        
    - label: "Services"
      name: "services"
      file: "content/services.md"
      fields:
        - { label: "Title", name: "title", required: false, widget: "string"}
        - { label: "Body", name: "body", required: false, widget: "markdown"}
        - label: Services
          name: services
          widget: list
          fields:
            - { label: Service Name, name: service, widget: text }
            - { label: Service Price, name: price, widget: text }
            - { label: Description, name: description, widget: string }
        
    - label: "Gallery"
      name: "gallery"
      file: "content/gallery.md"
      fields:
        - { label: "Title", name: "title", required: false, widget: "string"}
        - { label: "Message", name: "message", widget: "string"}
    - label: "Contact"
      name: "contact"
      file: "content/contact.md"
      fields:
        - { label: "Title", name: "title", required: false, widget: "string"}
        - { label: "Message", name: "message", widget: "string"}
        
    - label: "FAQ"
      name: "faq"
      file: "content/faq.md"
      fields:
        - { label: "Title", name: "title", required: false, widget: "string"}
        - { label: "Body", name: "body", required: false, widget: "markdown"}
        - label: "Questions and Answers"
          name: "faqs"
          widget: "list"
          fields:
            - {label: Question, name: question, widget: text, default: "[write the question here]"}
            - {label: Answer, name: answer, widget: text, default: "[write the answer here]"}